datasets:
  train:
    batch_size_per_gpu: 8
    dataroot_gt: /kaggle/input/d/timmothyfarrel/data-latih-sistem/data_latih_sistem/train/train_HR
    dataroot_lq: /kaggle/input/d/timmothyfarrel/data-latih-sistem/data_latih_sistem/train/train_LR
    dataset_enlarge_ratio: 2
    filename_tmpl: '{}'
    gt_size: 128
    io_backend:
      type: disk
    name: Train_Potato
    num_worker_per_gpu: 4
    prefetch_mode: null
    type: PairedImageDataset
    use_hflip: true
    use_rot: true
  val:
    dataroot_gt: /kaggle/input/d/timmothyfarrel/data-latih-sistem/data_latih_sistem/val/val_HR
    dataroot_lq: /kaggle/input/d/timmothyfarrel/data-latih-sistem/data_latih_sistem/val/val_LR
    io_backend:
      type: disk
    name: Val_Potato
    type: PairedImageDataset
dist_params:
  backend: nccl
  port: 29500
logger:
  print_freq: 25
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: null
    resume_id: null
manual_seed: 42
model_type: ESRGANModel
name: ESRGAN_PerceptualDominant
network_d:
  num_feat: 64
  num_in_ch: 3
  type: VGGStyleDiscriminator
network_g:
  num_block: 23
  num_feat: 64
  num_in_ch: 3
  num_out_ch: 3
  type: RRDBNet
num_gpu: 1
path:
  pretrain_network_g: /kaggle/input/esrgan_x4_pretrained/pytorch/default/1/ESRGAN_SRx4_DF2KOST_official-ff704c30.pth
  resume_state: null
  strict_load_g: true
scale: 4
train:
  ema_decay: 0.999
  gan_opt:
    fake_label_val: 0.0
    gan_type: vanilla
    loss_weight: 0.001
    real_label_val: 1.0
    type: GANLoss
  net_d_init_iters: 0
  net_d_iters: 1
  optim_d:
    betas:
    - 0.9
    - 0.99
    lr: 0.0001
    type: Adam
    weight_decay: 0
  optim_g:
    betas:
    - 0.9
    - 0.99
    lr: 0.0001
    type: Adam
    weight_decay: 0
  perceptual_opt:
    criterion: l1
    layer_weights:
      conv5_4: 1
    perceptual_weight: 1.0
    range_norm: false
    style_weight: 0
    type: PerceptualLoss
    use_input_norm: true
    vgg_type: vgg19
  pixel_opt:
    loss_weight: 0.01
    reduction: mean
    type: L1Loss
  scheduler:
    gamma: 0.5
    milestones:
    - 5000
    - 10000
    - 15000
    type: MultiStepLR
  total_iter: 15000
  warmup_iter: -1
val:
  metrics:
    niqe:
      better: lower
      crop_border: 4
      test_y_channel: false
      type: calculate_niqe
    psnr:
      better: higher
      crop_border: 4
      test_y_channel: false
      type: calculate_psnr
    ssim:
      better: higher
      crop_border: 4
      test_y_channel: false
      type: calculate_ssim
  save_img: true
  val_freq: 1000
